name: Build Web

on:
  push:
  pull_request:
    branches: ["master"]

env:
  NODEJS_VERSION: 20.17.0
  ASPNETCORE_ENVIRONMENT: Development
  USER_SECRETS: ${{ secrets.USERSECRETS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Install dependencies
        working-directory: ./Web
        run: npm install

      - name: Lint & Build
        working-directory: ./Web
        run: |
          npm run lint
          npm run build
