name: Build API

on:
  push:
  pull_request:
    branches: ["master"]

env:
  ASPNETCORE_ENVIRONMENT: Development
  USER_SECRETS: ${{ secrets.USERSECRETS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore workload and dependencies
        working-directory: ./API
        run: |
          dotnet workload restore
          dotnet restore API.csproj

      - name: Build
        working-directory: ./API
        run: |
          echo $USER_SECRETS > secrets.json
          dotnet build --no-restore API.csproj
