name: Build

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore API's workload and dependencies
        working-directory: ./API
        run: |
          dotnet workload restore &&
          dotnet restore API.csproj

      - name: Build
        working-directory: ./API
        run: dotnet build --no-restore API.csproj
