name: Test

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore API's workload and dependencies
        working-directory: ./API
        run: |
          dotnet workload restore
          dotnet restore API.csproj

      - name: Build & Run API
        working-directory: ./API
        env:
          ASPNETCORE_ENVIRONMENT: Development
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo $SUPER_SECRET > secrets.json
          dotnet build --no-restore API.csproj
          dotnet run --project ./API.csproj &

      - name: Restore Tests's workload and dependencies
        working-directory: ./Tests
        run: |
          dotnet workload restore
          dotnet restore

      - name: Build & Run Tests
        working-directory: ./Tests
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo $SUPER_SECRET > secrets.json
          dotnet test --no-restore
