name: Test

on:
  push:
  pull_request:
    branches: ["master"]

env:
  NUNIT_CONSOLE_VERSION: 3.18.1

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore API's workload and dependencies
        working-directory: ./API
        run: |
          dotnet workload restore
          dotnet restore API.csproj

      - name: Build & Run API
        working-directory: ./API
        env:
          ASPNETCORE_ENVIRONMENT: Development
        run: |
          dotnet build --no-restore API.csproj
          dotnet run --project ./API.csproj &

      - name: Install NUnit.Console
        working-directory: ./Tests
        run: nuget install NUnit.Console -Version $env:NUNIT_CONSOLE_VERSION -DirectDownload -OutputDirectory .

      - name: Restore Tests's workload and dependencies
        working-directory: ./Tests
        run: |
          dotnet workload restore
          dotnet restore

      - name: Build & Run Tests
        working-directory: ./Tests
        run: |
          dotnet build --no-restore
          $runner = "./NUnit.ConsoleRunner.$env:NUNIT_CONSOLE_VERSION/tools/nunit3-console.exe"
          & $Runner Tests.csproj
